language: python
python:
- '3.6'
install:
- pip install -r requirements.txt --quiet
- pip install pytest
- pip install pytest-cov
- pip install coverage
- pip install mkdocs
- pip install mkdocs-material
script:
- pytest tests --cov=autokaggle --cov-report xml:coverage.xml
- sh docs.sh
after_success:
- pip install python-coveralls && coveralls
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: docs/
  target-branch: gh-pages
  on:
    branch: master
